name: Generate Help File

on:
  push:
    branches: [main]

jobs:
  generate-help:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4"

      - name: Run script to update help file
        run: lua scripts/gen-help.lua

      - name: Commit changes if help file updated
        run: |
          git config user.name "mark9 bot"
          git config user.email "bot@users.noreply.github.com"
          git diff --quiet || (git add doc/mark9.txt && git commit -m "docs: update mark9.txt from README" && git push)
